language: java
cache:
 directories:
 - $HOME/.m2
jdk:
- oraclejdk8
script:
- cd destinationservice
- mvn clean package
sudo: required
services:
- docker
script:
- docker login -u driesverreydt -p Verreydt1991
- mvn clean package docker:build
- docker push driesverreydt/travelagencydestinationservice:latest